### ISSUE TITLE
你好，代码写的不错，发现一个问题，每行的图片个数不一样的时候，显示异常。

### ISSUE THREAD

**Issue by zhangliang5** [Sky-star/SkyMicroblogDemo#1]
你好，代码写的不错，发现一个问题，每行的图片个数不一样的时候，显示异常。
例如，第一行显示1张，第二行2张，第三行3张，第4行4张，依次类推，再显示的时候，就乱了，看看是什么问题

**Comment by Sky-star** [comment]
你好，我测试了一下， 并没有问题， 这个图片的赋值需要同时设置在cellForRow方法和highForRow方法中设置。如果还是发现有问题请发一份截图或者源码好么。

**Comment by zhangliang5** [comment]
你好，你的邮件地址是多少啊

**Comment by Sky-star** [comment]
417941258@qq.com
